production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  # add here your database-name (e.g. 'postfixadmin')
  database: database_name
  pool: 5
  # add here your database-user who is allowed to use the database above (e.g. 'postfixadmin')
  username: postfixadmin
  # Add here your password (plain-text) of the user above.
  password: mysecret password
  # add here your server, where MySQL is running
  socket: mydomain.com

# If youre developing this app you can add your additional databases here, of course!